language: java
services:
  - postgresql
before_script:
  - psql -c 'create database quote;' -U postgres
deploy:
  provider: heroku
  api-key:
    secure: 5f3b4fa1-079f-4391-bd91-ab06a6ede458
  app: spring-rest-otot
